# log配置
logging:
  level:
    root: info
    com.ignite.project: debug

# App服务配置
spring:
  application:
    name: ZIgnite
  profiles:
    active: dev

ignite:
  config:
    igniteInstanceName: SpringApplicationNode
    workDirectory: d:/tmp/ignite/work
    peerClassEnabled: true
    gridCfgPath: resources/default-config-client.xml
    discovery:
      #spiType: zookeeper
      #connection: data-master01:2181,data-worker01:2181,data-worker02:2181
      spiType: TcpMulticast
      connection: data-master01:47500,data-worker01:47500,data-worker02:47500
      socketTimeout: 30000
      connectionRecoveryTimeout: 100000
    connector:
      port: 10800
      portRange: 4



